branch-defaults:
  default:
    environment: null
deploy:
  artifact: contact-1.0.zip
  version: contat-1.0
environment-defaults:
  production:
    branch: null
    repository: null
global:
  application_name: contact
  branch: null
  default_ec2_keyname: moj-publiczny-klucz-ssh
  default_platform: python-2.7
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
